version: '3'

services:

  grafana:
    image: grafana/grafana:6.5.1
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.neic.dk`)
      - traefik.http.routers.grafana.entrypoints=internal-https
      - traefik.http.routers.grafana.tls.certResolver=le
      - traefik.http.routers.grafana.tls.domains[0].main=neic.dk
      - traefik.http.routers.grafana.tls.domains[0].sans=*.neic.dk
      - traefik.http.services.grafana.loadbalancer.server.port=3000

  prometheus:
    image: prom/prometheus:v2.14.0
    restart: unless-stopped
    command: [ "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles", "--storage.tsdb.retention.time=100y" ]
    volumes:
      - prometheus-tsdb:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/rules.yml:/etc/prometheus/rules.yml
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=Host(`prometheus.neic.dk`)
      - traefik.http.routers.prometheus.entrypoints=internal-https
      - traefik.http.routers.prometheus.tls.certResolver=le
      - traefik.http.routers.prometheus.tls.domains[0].main=neic.dk
      - traefik.http.routers.prometheus.tls.domains[0].sans=*.neic.dk
      - traefik.http.services.prometheus.loadbalancer.server.port=9090

  prometheus-blackbox-exporter:
    image: prom/blackbox-exporter:v0.16.0
    volumes:
      - ./config/prometheus/blackbox.yml:/etc/blackbox_exporter/config.yml

volumes:
  grafana:
  prometheus-tsdb:
